import Head from 'next/head'
import Img from 'next/image'
import Timer from '../components/Countdown/Timer'
// import Optin from '../components/Optin/Optin'
import Preloader from '../components/Preloader/Preloader'
import Logo from '../../public/img/logo.png'

export default function Home() {
  return (
    <div className="App">
      <Head>
        <title>Orras | Comming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
      <div className="image-ff">
      
      <Img  height="150px" width="150px" fixed  alt="..." src={Logo}/>
      </div>
        <h1>
          Coming Soon ...
        </h1>
        {/* <Timer /> */}
        {/* <Optin /> */}
        <Preloader />
      </div>
    </div>
  )
}
