import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Hero from '../components/Hero'
import How from '../components/How'
import Illustration from '../components/Illustration'
import Navigation from '../components/Navigation'
import Testimonial from '../components/Testimonial'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Hero />
      <About />
      <How />
      <Illustration />
      <Testimonial />
    </div>
  )
}
